import { CommandDefinition } from './types';

export const DEFAULT_COMMANDS: CommandDefinition[] = [
  // ── Keyboard Keys ──
  { phrase: 'enter', action: { type: 'key', key: 'Return' }, category: 'keyboard', description: 'Press Enter' },
  { phrase: 'tab', action: { type: 'key', key: 'Tab' }, category: 'keyboard', description: 'Press Tab' },
  { phrase: 'backspace', action: { type: 'key', key: 'Backspace' }, category: 'keyboard', description: 'Press Backspace' },
  { phrase: 'delete', action: { type: 'key', key: 'Delete' }, category: 'keyboard', description: 'Press Delete' },
  { phrase: 'escape', action: { type: 'key', key: 'Escape' }, category: 'keyboard', description: 'Press Escape' },
  { phrase: 'space bar', action: { type: 'key', key: 'Space' }, category: 'keyboard', description: 'Press Space' },

  // ── Navigation ──
  { phrase: 'arrow up', action: { type: 'key', key: 'Up' }, category: 'navigation', description: 'Arrow up' },
  { phrase: 'arrow down', action: { type: 'key', key: 'Down' }, category: 'navigation', description: 'Arrow down' },
  { phrase: 'arrow left', action: { type: 'key', key: 'Left' }, category: 'navigation', description: 'Arrow left' },
  { phrase: 'arrow right', action: { type: 'key', key: 'Right' }, category: 'navigation', description: 'Arrow right' },
  { phrase: 'home', action: { type: 'key', key: 'Home' }, category: 'navigation', description: 'Home key' },
  { phrase: 'end', action: { type: 'key', key: 'End' }, category: 'navigation', description: 'End key' },
  { phrase: 'page up', action: { type: 'key', key: 'PageUp' }, category: 'navigation', description: 'Page up' },
  { phrase: 'page down', action: { type: 'key', key: 'PageDown' }, category: 'navigation', description: 'Page down' },

  // ── Editing ──
  { phrase: 'select all', action: { type: 'combo', keys: ['Control', 'a'] }, category: 'editing', description: 'Select all (Ctrl+A)' },
  { phrase: 'copy', action: { type: 'combo', keys: ['Control', 'c'] }, category: 'editing', description: 'Copy (Ctrl+C)' },
  { phrase: 'paste', action: { type: 'combo', keys: ['Control', 'v'] }, category: 'editing', description: 'Paste (Ctrl+V)' },
  { phrase: 'cut', action: { type: 'combo', keys: ['Control', 'x'] }, category: 'editing', description: 'Cut (Ctrl+X)' },
  { phrase: 'undo', action: { type: 'combo', keys: ['Control', 'z'] }, category: 'editing', description: 'Undo (Ctrl+Z)' },
  { phrase: 'redo', action: { type: 'combo', keys: ['Control', 'Shift', 'z'] }, category: 'editing', description: 'Redo (Ctrl+Shift+Z)' },

  // ── Punctuation ──
  { phrase: 'period', action: { type: 'text', text: '.' }, category: 'punctuation', description: 'Type period' },
  { phrase: 'dot', action: { type: 'text', text: '.' }, category: 'punctuation', description: 'Type period' },
  { phrase: 'comma', action: { type: 'text', text: ',' }, category: 'punctuation', description: 'Type comma' },
  { phrase: 'question mark', action: { type: 'text', text: '?' }, category: 'punctuation', description: 'Type question mark' },
  { phrase: 'exclamation point', action: { type: 'text', text: '!' }, category: 'punctuation', description: 'Type exclamation' },
  { phrase: 'exclamation mark', action: { type: 'text', text: '!' }, category: 'punctuation', description: 'Type exclamation' },
  { phrase: 'colon', action: { type: 'text', text: ':' }, category: 'punctuation', description: 'Type colon' },
  { phrase: 'semicolon', action: { type: 'text', text: ';' }, category: 'punctuation', description: 'Type semicolon' },
  { phrase: 'open paren', action: { type: 'text', text: '(' }, category: 'punctuation', description: 'Type open parenthesis' },
  { phrase: 'close paren', action: { type: 'text', text: ')' }, category: 'punctuation', description: 'Type close parenthesis' },
  { phrase: 'open bracket', action: { type: 'text', text: '[' }, category: 'punctuation', description: 'Type open bracket' },
  { phrase: 'close bracket', action: { type: 'text', text: ']' }, category: 'punctuation', description: 'Type close bracket' },
  { phrase: 'open brace', action: { type: 'text', text: '{' }, category: 'punctuation', description: 'Type open brace' },
  { phrase: 'close brace', action: { type: 'text', text: '}' }, category: 'punctuation', description: 'Type close brace' },
  { phrase: 'open quote', action: { type: 'text', text: '"' }, category: 'punctuation', description: 'Type open quote' },
  { phrase: 'close quote', action: { type: 'text', text: '"' }, category: 'punctuation', description: 'Type close quote' },
  { phrase: 'single quote', action: { type: 'text', text: "'" }, category: 'punctuation', description: 'Type single quote' },
  { phrase: 'apostrophe', action: { type: 'text', text: "'" }, category: 'punctuation', description: 'Type apostrophe' },
  { phrase: 'hyphen', action: { type: 'text', text: '-' }, category: 'punctuation', description: 'Type hyphen' },
  { phrase: 'dash', action: { type: 'text', text: '—' }, category: 'punctuation', description: 'Type em dash' },
  { phrase: 'ellipsis', action: { type: 'text', text: '…' }, category: 'punctuation', description: 'Type ellipsis' },
  { phrase: 'at sign', action: { type: 'text', text: '@' }, category: 'punctuation', description: 'Type at sign' },
  { phrase: 'hashtag', action: { type: 'text', text: '#' }, category: 'punctuation', description: 'Type hash' },
  { phrase: 'dollar sign', action: { type: 'text', text: '$' }, category: 'punctuation', description: 'Type dollar sign' },
  { phrase: 'percent', action: { type: 'text', text: '%' }, category: 'punctuation', description: 'Type percent' },
  { phrase: 'asterisk', action: { type: 'text', text: '*' }, category: 'punctuation', description: 'Type asterisk' },
  { phrase: 'slash', action: { type: 'text', text: '/' }, category: 'punctuation', description: 'Type slash' },
  { phrase: 'backslash', action: { type: 'text', text: '\\' }, category: 'punctuation', description: 'Type backslash' },
  { phrase: 'pipe', action: { type: 'text', text: '|' }, category: 'punctuation', description: 'Type pipe' },
  { phrase: 'tilde', action: { type: 'text', text: '~' }, category: 'punctuation', description: 'Type tilde' },
  { phrase: 'underscore', action: { type: 'text', text: '_' }, category: 'punctuation', description: 'Type underscore' },
  { phrase: 'equals', action: { type: 'text', text: '=' }, category: 'punctuation', description: 'Type equals' },
  { phrase: 'plus sign', action: { type: 'text', text: '+' }, category: 'punctuation', description: 'Type plus' },
  { phrase: 'less than', action: { type: 'text', text: '<' }, category: 'punctuation', description: 'Type less than' },
  { phrase: 'greater than', action: { type: 'text', text: '>' }, category: 'punctuation', description: 'Type greater than' },
  { phrase: 'ampersand', action: { type: 'text', text: '&' }, category: 'punctuation', description: 'Type ampersand' },

  // ── Formatting ──
  { phrase: 'new line', action: { type: 'key', key: 'Return' }, category: 'formatting', description: 'New line' },
  { phrase: 'new paragraph', action: { type: 'sequence', actions: [{ type: 'key', key: 'Return' }, { type: 'key', key: 'Return' }] }, category: 'formatting', description: 'Double Enter' },
  { phrase: 'capitalize', action: { type: 'modifier', modifier: 'capitalize' }, category: 'formatting', description: 'Capitalize next word' },
  { phrase: 'all caps', action: { type: 'modifier', modifier: 'allCaps' }, category: 'formatting', description: 'Uppercase next word' },
  { phrase: 'no caps', action: { type: 'modifier', modifier: 'noCaps' }, category: 'formatting', description: 'Lowercase next word' },
];
